import { Metadata } from "next"

export const metadata: Metadata = {
    title: 'About | Online Courses',
    description: 'Generated by create next app',
}

export default function About () {
    return <h3>Контент о нас</h3>
}